### ISSUE TITLE
Functionality to be able to: find a specific user by name or id

### ISSUE THREAD

**Issue by StephenJayYoung** [wbyoung/admit-one#4] opened 2014-11-14 19:59 UTC
We  want to be able to find a specific user by name or id, but the way in which admit-one is written, it requires that the user to be signed in before being able to access this data. 

Signing in should be required to change a profile, but not to use it.

Example:
path: example/users/steveyoung (show profile details)
path:example/users/331(id) (show profile details)

**Comment by wbyoung** [comment] 2014-11-15 00:32
Duplicate of #2.

**Closed as completed by wbyoung** 2014-11-15 00:32 UTC
